---
engines:
  pylint:
    # pylintpython3 is used instead
    exclude_paths:
      - "**"
  tsqllint:
    # for Microsoft only
    exclude_paths:
      - "**"
exclude_paths:
  - ".stylelint/indentationEx.js"
