{
  "jobs": {
    "codacy-security-scan": {
      "permissions": {
        "actions": "read",
        "contents": "read",
        "security-events": "write"
      },
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "run": "sudo apt-get --purge -y install jq"
        },
        {
          "uses": "actions/checkout@v3.3.0"
        },
        {
          "uses": "codacy/codacy-analysis-cli-action@v4.2.0",
          "with": {
            "format": "sarif",
            "gh-code-scanning-compat": true,
            "max-allowed-issues": 2147483647,
            "output": "results.sarif",
            "project-token": "${{ secrets.CODACY_PROJECT_TOKEN }}",
            "verbose": true
          }
        },
        {
          "run": "jq -c '.runs |= map(select((.results | length) > 0))' <results.sarif >onlyresults.sarif"
        },
        {
          "uses": "github/codeql-action/upload-sarif@codeql-bundle-20230105",
          "with": {
            "sarif_file": "onlyresults.sarif"
          }
        }
      ]
    }
  },
  "name": "Codacy Security Scan",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "workflow_dispatch": null
  },
  "permissions": {
    "contents": "read"
  }
}
