{
  "jobs": {
    "codacy-security-scan": {
      "permissions": {
        "actions": "read",
        "contents": "read",
        "security-events": "write"
      },
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.1.1"
        },
        {
          "uses": "codacy/codacy-analysis-cli-action@v4.3.0",
          "with": {
            "format": "sarif",
            "gh-code-scanning-compat": true,
            "max-allowed-issues": 2147483647,
            "output": "results.sarif",
            "project-token": "${{ secrets.CODACY_PROJECT_TOKEN }}",
            "verbose": true
          }
        },
        {
          "uses": "actions/upload-artifact@v4.2.0",
          "with": {
            "name": "SARIF",
            "path": "results.sarif"
          }
        },
        {
          "run": "jq -c '.runs |= unique_by({tool, invocations, results})' <results.sarif >editedresults.sarif\nrm results.sarif\nmkdir results.sarif\njq -c '.runs |= .[0:15]' <editedresults.sarif >results.sarif/1.sarif\njq -c '.runs |= .[15:]' <editedresults.sarif >results.sarif/2.sarif\n"
        },
        {
          "uses": "github/codeql-action/upload-sarif@v3",
          "with": {
            "sarif_file": "results.sarif"
          }
        }
      ]
    }
  },
  "name": "Codacy Security Scan",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "workflow_dispatch": null
  },
  "permissions": {
    "contents": "read"
  }
}
